"""add user auth fields

Revision ID: aa4b8fb6e8f0
Revises: 4045f1e83d90
Create Date: 2026-06-11 21:21:35.358225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4b8fb6e8f0'
down_revision: Union[str, Sequence[str], None] = '4045f1e83d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        # server_default: mevcut kullanıcı satırları için varsayılan rol ('viewer').
        batch_op.add_column(sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='userrole'), nullable=False, server_default='viewer'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
