"""kuruma ozel alanlar

Revision ID: d9d9c213fb13
Revises: 30dbf2d7071e
Create Date: 2026-08-04 17:06:10.751971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d9c213fb13'
down_revision: Union[str, Sequence[str], None] = '30dbf2d7071e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demirbas_no', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('muhasebe_kodu', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('fatura_no', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('warranty_end', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('barkod', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('imei', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('mac_address', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('hostname', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('telefon_no', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('sim_no', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('operator', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_assets_barkod'), ['barkod'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_demirbas_no'), ['demirbas_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_imei'), ['imei'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_mac_address'), ['mac_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_warranty_end'), ['warranty_end'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tckn', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('sube', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('telefon', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('ise_giris', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_tckn'), ['tckn'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tckn'))
        batch_op.drop_column('ise_giris')
        batch_op.drop_column('telefon')
        batch_op.drop_column('sube')
        batch_op.drop_column('tckn')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_warranty_end'))
        batch_op.drop_index(batch_op.f('ix_assets_mac_address'))
        batch_op.drop_index(batch_op.f('ix_assets_imei'))
        batch_op.drop_index(batch_op.f('ix_assets_demirbas_no'))
        batch_op.drop_index(batch_op.f('ix_assets_barkod'))
        batch_op.drop_column('operator')
        batch_op.drop_column('sim_no')
        batch_op.drop_column('telefon_no')
        batch_op.drop_column('hostname')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('mac_address')
        batch_op.drop_column('imei')
        batch_op.drop_column('barkod')
        batch_op.drop_column('warranty_end')
        batch_op.drop_column('fatura_no')
        batch_op.drop_column('muhasebe_kodu')
        batch_op.drop_column('demirbas_no')

    # ### end Alembic commands ###
