"""lokasyon proje kodu

Revision ID: e7e251e1fd54
Revises: d9d9c213fb13
Create Date: 2026-08-07 10:55:54.602212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e251e1fd54'
down_revision: Union[str, Sequence[str], None] = 'd9d9c213fb13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proje_kodu', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_locations_proje_kodu'), ['proje_kodu'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_proje_kodu'))
        batch_op.drop_column('proje_kodu')

    # ### end Alembic commands ###
